# Attack on Titan Season 1 Episode 1
title = "To You, in 2000 Years: The Fall of Shiganshina, Part 1"
description = "For over a century, humans have been living in settlements surrounded by enormous walls, protecting them from the giant humanoids known as Titans. Young Eren Yeager lives in peace until the day a massive Titan breaches the wall."
air_date = "2013-04-07"
duration = "24 min"

# Episode-specific metadata
synopsis = "The series begins with Eren Yeager, his adoptive sister Mikasa Ackerman, and their friend Armin Arlert living in the town of Shiganshina, which is located on the outermost of three circular walls protecting humanity from Titans."

# Production notes
director = "Tetsuro Araki"
writer = "Yasuko Kobayashi"
storyboard = "Tetsuro Araki"

# Viewer ratings
rating = 8.7
total_votes = 12534